"""empty message

Revision ID: 05efe023a4ad
Revises: 59b513b8d184
Create Date: 2024-10-11 01:19:03.128970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05efe023a4ad'
down_revision = '59b513b8d184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
